# Generated by Django 6.0.4 on 2026-04-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('price', models.IntegerField(verbose_name='Precio en CLP')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
